### ISSUE TITLE
tests continue after earlier failures

### ISSUE THREAD

**Issue by kkallday** [cloudfoundry/wats#11]
Hi,

I've noticed that when a `cf` command in a test fails, the test scenario will continue and fail at later point in time. Debugging the tests becomes difficult since the test says it fails on line _x_, however the _real_ failure is on line _x-100_. Here's an example:

1. The test output looks like this:
```
[2017-05-18 20:20:11.80 (UTC)]> cf start WATS-1-APP-4912b13f-f23c-4938-4 
Starting app WATS-1-APP-4912b13f-f23c-4938-4 in org WATS-1-ORG-511dc484-7351-4300-4 / space WATS-1-SPACE-abd528c8-b0f0-4a36-6 as WATS-USER-1-2017_05_18-20h14m20.076s...
Downloading hwc_buildpack...
Downloaded hwc_buildpack
Creating container
Successfully created container
Downloading app package...
Downloaded app package (953.8K)
       HWC version 3.0.0
-----> Installing HWC
       Copy [C:\containerizer\DBAACEF8B10839197B\user\tmp\buildpacks\A580FCA95716F38D4C31649E54AFACBA\dependencies\https___buildpacks.cloudfoundry.org_dependencies_hwc_hwc-3.0.0-windows-amd64-acb65777.zip]
-----> Hwc Buildpack version 2.3.4
-----> Installing hwc 3.0.0
Exit status 0
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (167B)
Uploaded droplet (2M)
Uploading complete
Destroying container
Successfully destroyed container

0 of 1 instances running, 1 crashed
FAILED
Start unsuccessful

TIP: use 'cf logs WATS-1-APP-4912b13f-f23c-4938-4 --recent' for more information

[2017-05-18 20:20:30.81 (UTC)]> cf start WATS-1-APP-4912b13f-f23c-4938-4 
App WATS-1-APP-4912b13f-f23c-4938-4 is already started
STEP: verifying it's up

[2017-05-18 20:20:31.81 (UTC)]> curl -k -H Expect: -s http://WATS-1-APP-4912b13f-f23c-4938-4.apps.topaz-scorpion.gcp.releng.cf-app.com/ 
404 Not Found: Requested route ('wats-1-app-4912b13f-f23c-4938-4.apps.topaz-scorpion.gcp.releng.cf-app.com') does not exist.

<Lots of 404s repeating>
```

1. Test failure says:
```
• Failure in Spec Setup (BeforeEach) [92.043 seconds]
A running application
/tmp/build/2b769089/wats/src/wats/dynamic_info_test.go:23
  can show crash events [BeforeEach]
  /tmp/build/2b769089/wats/src/wats/dynamic_info_test.go:22

  Timed out after 60.000s.
  Expected
      <string>: 404 Not Found: Requested route ('wats-1-app-4912b13f-f23c-4938-4.apps.topaz-scorpion.gcp.releng.cf-app.com') does not exist.
      
  to contain substring
      <string>: hello i am nora

  /tmp/build/2b769089/wats/src/wats/helpers_test.go:101
```

1. Based on the test failure, this seems to be an issue with routes for apps running on the Windows Diego cell not registering. However, by looking many lines above the line describing the test failure you'll see that app "crashed" after `cf start`.

Given the app did not start properly with `cf start`, I would expect the test failure to state `cf start ...` failed, not that the `curl` returned a 404 and the test did not see `hello i am nora`. I'm not sure if the CF CLI isn't responding with a non-zero status code or if the test helper library is incorrectly reporting this as a 0 status code. As more features and this test suite grows, I could see this negatively affecting teams like releng or relint by making it harder to debug these issue without requiring the greenhouse team's assistance.

**Comment by sunjayBhatia** [comment]
@kkallday we just pushed a commit to `develop` that should hopefully address this

When it makes its way to master, let us know if it fixes some of the stuff you're seeing?
