### ISSUE TITLE
WATs should wait for `update-quota` command to finish

### ISSUE THREAD

**Issue by jvshahid** [cloudfoundry/wats#14]
Looks like we don't wait for the the `update-quota` command to finish [here](https://github.com/cloudfoundry/wats/blob/master/src/wats/helpers_test.go#L133) which sometimes will cause `cf logout` to run in parallel and cause the `update-quota` command to fail with error:

```
[2017-07-19 18:48:30.42 (UTC)]> cf update-quota WATS-1-QUOTA-01536ba1-05d7-4e52-6 -m 99999G 

[2017-07-19 18:48:30.42 (UTC)]> cf logout 
Logging out...
OK
FAILED
Not logged in. Use 'cf login' to log in.
```

This has caused test failures in [this build](https://diego.ci.cf-app.com/teams/main/pipelines/main/jobs/warp-drive-run-wats/builds/304)

**Comment by crawsible** [comment]
Thanks @jvshahid, scheduling this.

**Comment by sunjayBhatia** [comment]
@jvshahid I think we just need to change the `update-quota` line to

```
		Eventually(cf.Cf("update-quota", quota.Entity.Name, "-m", memoryLimit), DEFAULT_TIMEOUT).Should(gexec.Exit(0))
```

so that we actually wait for the command to exit before the `AsUser` logs us out otherwise the `gexec.Session` returned by `cf.Cf()` is just left to run as it pleases without anything waiting for it to finish

**Comment by crawsible** [comment]
@sunjayBhatia maybe we should follow the pattern [here](https://github.com/cloudfoundry/wats/blob/master/src/wats/helpers_test.go#L84) and use `cf.Cf(...).Wait(<timeout>)` instead?

**Comment by crawsible** [comment]
@jvshahid We made this change on master.
