### ISSUE TITLE
Consider alternative dependency management tools

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/wats#19]
We were stuck for some time trying to run `wats` locally. The culprit was the `vendor` directory is not populated by a normal `git clone`, you need to run `git submodule update --init --recursive` first to download all dependencies. It is also a little surprising that this repo is structured as a `GOPATH` rather than living in your system `GOPATH`.

Instead of submoduling in deps, could you instead either vendor in the flat files so things work out of the box or better yet use a dependency management tool like [dep](https://github.com/golang/dep)?

**Comment by sesmith177** [comment]
@ljfranklin we have switch WATS from submodules -> dep for vendored directories as of 6dd17345be5425148c35d85ab330cd2139296579

We are not going to change this repo from being structured as a GOPATH as of yet, since it would break anyone currently running WATS in CI
