### ISSUE TITLE
WATs should open a tcp connection to the secure address instead of trying to do an HTTP request

### ISSUE THREAD

**Issue by jvshahid** [cloudfoundry/wats#20]
*Description*

Currently [Nora curl endpoint](https://github.com/cloudfoundry/wats/blob/master/assets/nora/Nora/Controllers/InstancesController.cs#L142-L165) is trying to do an HTTP request to the secure address. This is problematic for those who upgrade to bbl v5 since the director `25555` port is blocked. We tried to change the secure address to use the jumpbox sshd port `22` but that failed with an `protocol violation` error.

*Expected behavior*

WATs pass on an environment deployed with bbl v5.7.3

*Actual behavior*

WATs is failing with `{"stderr":"The operation has timed out","return_code":1}`

When we try to use the jumpbox sshd we got the following error

```
{"stderr":"The server committed a protocol violation. Section=ResponseStatusLine","return_code":1}
```

**Comment by sunjayBhatia** [comment]
@jvshahid we added a `connect` endpoint and used it in the security group test, changes on master
