### ISSUE TITLE
verifying reported disk/memory usage test appears to be checking disk usage only once

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry/wats#7]
On [this line of the lifecycle test](https://github.com/cloudfoundry/wats/blob/master/src/wats/lifecycle_test.go#L115) it looks like the intention was to check disk over and over until the `CF_PUSH_TIMEOUT` is reached.  However, because the anonymous function is called immediately it does not check repeatedly.  Instead, it will check only once and then repeatedly check the float return value of the function (which won't ever change, since it was set the first and only time the function was called) until the timeout is reached.

**Comment by sunjayBhatia** [comment]
No longer calling the anonymous function immediately: https://github.com/cloudfoundry/wats/commit/39de616021f16ddea9984b3299839780ae50476c

Tests passed and merged to master: https://greenhouse.ci.cf-app.com/teams/main/pipelines/greenhouse/jobs/pesto-bosh-deploy-windows/builds/95
